---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: node_exporter
    groups:
      - node_exporter
  - name: haproxy_exporter
    groups:
      - haproxy_exporter
  - name: blackbox_exporter
    groups:
      - blackbox_exporter
  - name: mysql_exporter
    groups:
      - mysql_exporter
provisioner:
  name: ansible
  options:
    diff: True
    v: True
  playbooks:
    create: create.yml
    prepare: prepare.yml
    destroy: destroy.yml
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: goss
