---
- name: install node_exporter on all the instances
  hosts: all
  roles:
    - {role: ansible-prometheus-exporter}
- name: install haproxy_exporter on haproxy
  hosts: haproxy_exporter
  roles:
    - role: ansible-prometheus-exporter
      prometheus_exporter_name: haproxy_exporter
      prometheus_exporter_version: 0.9.0
      prometheus_exporter_config_flags:
        'haproxy.scrape-uri': 'http://admin:admin@instance-haproxy/haproxy?stats;csv'

- name: install blackbox_exporter on blackbox_exporter group
  hosts: blackbox_exporter
  roles:
    - role: ansible-prometheus-exporter
      prometheus_exporter_name: blackbox_exporter
      prometheus_exporter_version: 0.12.0

- name: install mysqld_exporter on mysqld_exporter group
  hosts: mysql_exporter
  roles:
    - role: ansible-prometheus-exporter
      prometheus_exporter_name: mysqld_exporter
      prometheus_exporter_version: 0.10.0
      prometheus_environment_variables:
        'DATA_SOURCE_NAME': 'monitoring_user:monitoring_v3ry_s3cretp4ss0rd@(hostname:3306)/'
